'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { Shield, Clock, ExternalLink, CheckCircle, AlertCircle, Loader2, Download, FileText } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface VerificationData {
  verified: boolean;
  capture: {
    id: string;
    url: string;
    title: string;
    contentHash: string;
    ipfsCID: string;
    ipfsUrl: string;
    otsStatus: string;
    createdAt: string;
    metadata?: any;
  };
  verification: {
    verified: boolean;
    message: string;
    ipfsIntact: boolean;
    blockHeight?: number;
    timestamp?: number;
  };
}

export default function VerifyPage() {
  const params = useParams();
  const id = params.id as string;
  
  const [data, setData] = useState<VerificationData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [upgrading, setUpgrading] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [generatingPDF, setGeneratingPDF] = useState(false);

  const fetchVerification = async () => {
    try {
      setLoading(true);
      const response = await fetch(`/api/verify?id=${id}`);
      const result = await response.json();
      
      if (!response.ok) {
        throw new Error(result.error || 'Verification failed');
      }
      
      setData(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setLoading(false);
    }
  };

  const handleUpgrade = async () => {
    setUpgrading(true);
    try {
      const response = await fetch('/api/verify', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id })
      });
      
      if (response.ok) {
        await fetchVerification();
      }
    } catch (err) {
      console.error('Upgrade failed:', err);
    } finally {
      setUpgrading(false);
    }
  };

  const handleDownloadProof = async () => {
    setDownloading(true);
    try {
      const response = await fetch(`/api/verify/download?id=${id}`);
      if (!response.ok) throw new Error('Download failed');
      
      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `timecapsule-${id}.ots`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('Download failed:', err);
      alert('Failed to download OTS proof');
    } finally {
      setDownloading(false);
    }
  };

  const handleDownloadReport = () => {
    if (!data) return;
    setGeneratingPDF(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      
      // HEADER
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.text("Digital Verification Report", pageWidth / 2, 20, { align: "center" });
      
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.text("Generated by TimeCapsule", pageWidth / 2, 28, { align: "center" });
      doc.setLineWidth(0.5);
      doc.line(10, 35, pageWidth - 10, 35);

      // EVIDENCE DETAILS
      let y = 50;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("1. Evidence Details", 10, y);
      y += 10;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`Capture ID: ${data.capture.id}`, 15, y);
      y += 7;
      doc.text(`Title: ${data.capture.title || "Untitled"}`, 15, y);
      y += 7;
      doc.text(`Original Source: ${data.capture.url || "Direct File Upload"}`, 15, y);
      y += 7;
      doc.text(`Capture Time: ${new Date(data.capture.createdAt).toLocaleString()}`, 15, y);
      y += 15;

      // INTEGRITY
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("2. Cryptographic Integrity", 10, y);
      y += 10;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text("SHA-256 Fingerprint (Content Hash):", 15, y);
      y += 5;
      doc.setFont("courier", "normal");
      doc.text(data.capture.contentHash, 15, y);
      y += 10;

      doc.setFont("helvetica", "normal");
      doc.text("IPFS Content Identifier (CID):", 15, y);
      y += 5;
      doc.setFont("courier", "normal");
      doc.text(data.capture.ipfsCID, 15, y);
      y += 15;

      // BLOCKCHAIN ANCHOR
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("3. Blockchain Verification", 10, y);
      y += 10;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.text(`Status: ${data.capture.otsStatus}`, 15, y);
      y += 7;
      
      if (data.verification.blockHeight) {
        doc.text(`Anchored in Bitcoin Block: #${data.verification.blockHeight}`, 15, y);
        y += 7;
        doc.text(`Bitcoin Timestamp: ${new Date((data.verification.timestamp || 0) * 1000).toLocaleString()}`, 15, y);
      } else {
        doc.text("Status: Pending Bitcoin Confirmation (Approx 10-60 mins)", 15, y);
      }
      
      y += 20;
      doc.setLineWidth(0.5);
      doc.line(10, y, pageWidth - 10, y);
      y += 10;

      // FOOTER
      doc.setFontSize(8);
      doc.setTextColor(100);
      doc.text("This document certifies that the evidence described above existed at the stated time.", 10, y);
      doc.text("Verification is secured by the Bitcoin Blockchain via OpenTimestamps.", 10, y + 5);

      doc.save(`verification-report-${data.capture.id.slice(0,8)}.pdf`);

    } catch (err) {
      console.error(err);
      alert("Failed to generate PDF");
    } finally {
      setGeneratingPDF(false);
    }
  };

  useEffect(() => {
    fetchVerification();
  }, [id]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="animate-spin mx-auto mb-4 text-blue-600 dark:text-blue-400" size={48} />
          <p className="text-gray-600 dark:text-gray-300">Verifying proof...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 flex items-center justify-center p-4">
        <div className="bg-white dark:bg-gray-800 p-8 rounded-lg shadow-lg max-w-md border border-gray-200 dark:border-gray-700">
          <AlertCircle className="text-red-600 mx-auto mb-4" size={48} />
          <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-2 text-center">Verification Failed</h1>
          <p className="text-gray-600 dark:text-gray-300 text-center">{error}</p>
        </div>
      </div>
    );
  }

  if (!data) return null;

  const isComplete = data.capture.otsStatus === 'COMPLETE';
  const isPending = data.capture.otsStatus === 'INCOMPLETE';
  
  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-100 mb-2">Proof Verification</h1>
          <p className="text-gray-600 dark:text-gray-300">Independent verification of digital evidence</p>
        </div>

        {/* Status Card */}
        <div className={`p-6 rounded-lg mb-6 ${
          isComplete ? 'bg-green-50 dark:bg-green-900 border-2 border-green-200 dark:border-green-700' : 'bg-yellow-50 dark:bg-yellow-900 border-2 border-yellow-200 dark:border-yellow-700'
        }`}>
          <div className="flex items-center gap-3 mb-4">
            {isComplete ? <CheckCircle className="text-green-600 dark:text-green-400" size={32} /> : <Clock className="text-yellow-600 dark:text-yellow-400" size={32} />}
            <div>
              <h2 className="text-xl font-semibold text-gray-900 dark:text-gray-100">
                {isComplete ? 'Fully Verified' : 'Pending Confirmation'}
              </h2>
              <p className={isComplete ? 'text-green-700 dark:text-green-300' : 'text-yellow-700 dark:text-yellow-300'}>{data.verification.message}</p>
            </div>
          </div>

          {isPending && (
            <div className="mt-4">
              <button onClick={handleUpgrade} disabled={upgrading} className="bg-yellow-600 hover:bg-yellow-700 dark:bg-yellow-500 dark:hover:bg-yellow-600 text-white px-4 py-2 rounded-lg text-sm font-medium disabled:opacity-50 flex items-center gap-2">
                {upgrading ? <><Loader2 className="animate-spin" size={16} /> Checking...</> : 'Check for Confirmation'}
              </button>
              <p className="text-xs text-gray-600 dark:text-gray-300 mt-2">Bitcoin blocks are mined approximately every 10 minutes. Check back soon!</p>
            </div>
          )}
        </div>

        {/* Instructions */}
        <div className="bg-blue-50 dark:bg-blue-900 rounded-lg border border-blue-200 dark:border-blue-700 p-6 mb-6">
          <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3 flex items-center gap-2">
            <Shield size={20} className="text-blue-600 dark:text-blue-400" /> Independent Verification
          </h3>
          <p className="text-sm text-gray-700 dark:text-gray-300 mb-4">Don't trust us? Verify the timestamp yourself without relying on TimeCapsule:</p>
          <ol className="list-decimal list-inside space-y-2 text-sm text-gray-700 dark:text-gray-300">
            <li>Download the OTS proof file using the button below</li>
            <li>Click on "View on IPFS", which will take you to the IPFS storage.</li>
            <li>Right click and save the file.</li>
            <li>Go to <a href="https://opentimestamps.org" target="_blank" rel="noopener noreferrer" className="text-blue-600 dark:text-blue-400 hover:underline font-medium">opentimestamps.org</a></li>
            <li>Click "Stamp & Verify" → Upload your .ots file and then the IPFS file.</li>
            <li>See Bitcoin block confirmation.</li>
          </ol>
        </div>

        {/* Capture Details Card */}
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-200 dark:border-gray-700 p-6 mb-6">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-4 gap-4">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100 flex items-center gap-2">
              <Shield size={20} /> Capture Details
            </h3>
            
            <button
              onClick={handleDownloadReport}
              disabled={generatingPDF}
              className="bg-gray-800 dark:bg-gray-700 hover:bg-gray-900 dark:hover:bg-gray-600 text-white px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition-colors disabled:opacity-70"
            >
              {generatingPDF ? <Loader2 className="animate-spin" size={16} /> : <FileText size={16} />}
              Export PDF Report
            </button>
          </div>

          <div className="space-y-4">
            <div>
              <label className="text-sm font-medium text-gray-700 dark:text-gray-300">Original URL</label>
              <a href={data.capture.url} target="_blank" rel="noopener noreferrer" className="text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 flex items-center gap-1 mt-1 break-all">
                {data.capture.title || data.capture.url} <ExternalLink size={14} />
              </a>
            </div>

            <div>
              <label className="text-sm font-medium text-gray-700 dark:text-gray-300">Content Hash (SHA-256)</label>
              <p className="font-mono text-xs text-gray-600 dark:text-gray-300 break-all mt-1 bg-gray-50 dark:bg-gray-700 p-2 rounded">{data.capture.contentHash}</p>
            </div>

            <div>
              <label className="text-sm font-medium text-gray-700 dark:text-gray-300">IPFS Storage</label>
              <div className="flex items-center gap-2 mt-1">
                <span className="font-mono text-xs text-gray-600 dark:text-gray-300">{data.capture.ipfsCID}</span>
                {data.verification.ipfsIntact && <CheckCircle className="text-green-600 dark:text-green-400" size={16} />}
              </div>
              <a href={`https://ipfs.io/ipfs/${data.capture.ipfsCID}`} target="_blank" rel="noopener noreferrer" className="text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 text-sm flex items-center gap-1 mt-1">
                View on IPFS <ExternalLink size={14} />
              </a>
            </div>

            <div>
              <label className="text-sm font-medium text-gray-700 dark:text-gray-300">Captured At</label>
              <p className="text-gray-600 dark:text-gray-300 mt-1">{new Date(data.capture.createdAt).toLocaleString()}</p>
            </div>

            {data.verification.blockHeight && (
              <div>
                <label className="text-sm font-medium text-gray-700 dark:text-gray-300">Bitcoin Block</label>
                <a href={`https://blockstream.info/block-height/${data.verification.blockHeight}`} target="_blank" rel="noopener noreferrer" className="text-blue-600 dark:text-blue-400 hover:text-blue-700 dark:hover:text-blue-300 flex items-center gap-1 mt-1">
                  #{data.verification.blockHeight} <ExternalLink size={14} />
                </a>
              </div>
            )}

            <div className="pt-4 border-t border-gray-200 dark:border-gray-700">
              <button onClick={handleDownloadProof} disabled={downloading} className="bg-blue-600 dark:bg-blue-500 hover:bg-blue-700 dark:hover:bg-blue-400 text-white px-4 py-2 rounded-lg text-sm font-medium disabled:opacity-50 flex items-center gap-2">
                {downloading ? <><Loader2 className="animate-spin" size={16} /> Downloading...</> : <><Download size={16} /> Download OTS Proof File</>}
              </button>
              <p className="text-xs text-gray-600 dark:text-gray-300 mt-2">Download the OpenTimestamps proof to verify independently</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
